#!/bin/sh
#
# chkconfig: 12345 11 89
# /etc/rc.d/init.d/babelroom-prime
#

RETVAL=0
BR=/home/br
CL=$BR/gits/clouds/clouds
TMPDIR=/tmp/br

# See how we were called.
case "$1" in
  start)
        (test -d $TMPDIR && rm -rf $TMPDIR)
        mkdir -p -m 0777 $TMPDIR
        (test -d $BR/.old_ikeys && rm -rf $BR/.old_ikeys) 2>$TMPDIR/init.err
        (test -d $BR/ikeys && mv $BR/ikeys $BR/.old_ikeys) 2>>$TMPDIR/init.err
        $CL/add_system_info.sh 2>>$TMPDIR/init.err
        runuser -l br -c $CL/babelroom-prime2.pl 2>>$TMPDIR/init.err
        test -f $BR/ikeys/autoprime && $CL/prime.pl 2>>$TMPDIR/init.err
        ;;
  stop|status|restart|reload|force-reload|condrestart|try-restart)
        ;;
  *)
        echo "Usage: babelroom-prime {start|stop|status|restart|reload|force-reload|condrestart|try-restart}"
        exit 2
esac
exit ${RETVAL}

