#!/bin/sh
#
# chkconfig: 12345 89 11
# /etc/rc.d/init.d/babelroom-run
#

RETVAL=0
BR=/home/br
ST=$BR/ikeys/startup
CM=$1

# See how we were called.
case "$CM" in
  start|status|restart|reload|force-reload|condrestart|try-restart)
        if [[ -f $ST ]]
        then
            while read line || [ "$line" ]; do
                for word in $line
                do
                    service $word $CM 2>>/tmp/br/babelroom-run.err
                done
            done < $ST
        fi
        ;;
  stop)
        if [[ -f $ST ]]
        then
            while read line || [ "$line" ]; do
                for word in $line
                do
                    if [ "$word" != "mysqld" ]
                    then
                        echo "Stopping $word"
                        service $word $CM 2>>/tmp/br/babelroom-run.err
                    fi
                done
            done < $ST
            sleep 5
            echo "Stopping mysqld"
            service mysqld stop 2>>/tmp/br/babelroom-run.err
        fi
        ;;
  *)
        echo "Usage: babelroom-run {start|stop|status|restart|reload|force-reload|condrestart|try-restart}"
        exit 2
esac
exit ${RETVAL}

